---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stream.aegis.io
  resources:
  - aegispipelines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - stream.aegis.io
  resources:
  - aegispipelines/finalizers
  verbs:
  - update
- apiGroups:
  - stream.aegis.io
  resources:
  - aegispipelines/status
  verbs:
  - get
  - patch
  - update
